# Site settings
title: Hystrix Examples
email: alexander.schwartz@gmx.net
description: "Showing what Hystrix can do for you."
baseurl: "/hystrix-examples"
url: "http://ahus1.github.io"
twitter_username: ahus1de
github_username:  ahus1

# Build settings
markdown: kramdown
permalink: pretty
